// <auto-generated />
namespace Forum.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Changemodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changemodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202010201151320_Change models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
