// <auto-generated />
namespace Forum.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Delcol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Delcol));
        
        string IMigrationMetadata.Id
        {
            get { return "202010101607013_Del col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
